# Generated by Django 4.2.6 on 2023-11-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("idade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("genero", models.IntegerField(choices=[(1, "Macho"), (2, "Fêmea")], default=1, verbose_name="Gênero")),
                ("status", models.CharField(max_length=20)),
                ("tipo_sanguineo", models.CharField(max_length=20)),
                (
                    "capa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="uploader.image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Animais",
                "verbose_name_plural": "Animais",
            },
        ),
        migrations.CreateModel(
            name="Especie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Espécie",
                "verbose_name_plural": "Espécies",
            },
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="racas", to="GrandeOrvalho.especie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=150)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "animais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="GrandeOrvalho.animais",
                    ),
                ),
            ],
        ),
    ]
