# Generated by Django 4.2.6 on 2023-11-07 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("GrandeOrvalho", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="animais",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animais",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="animais",
            name="raca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="animais", to="GrandeOrvalho.raca"
            ),
        ),
    ]
